version: '3.7'

services:
  transactions_db:
    image: mysql:8.0.18
    container_name: 'transactions-db'
    command: ['--default-time-zone=+8:00']
    environment:
      MYSQL_ROOT_PASSWORD: admin-root
    volumes: # docker volume ls, docker inspect {volumeId} to check location of volumes
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306 # hostPort:containerPort
    networks:
      - distributed-transactions
    # refer to: https://github.com/wurstmeister/kafka-docker, https://hub.docker.com/r/wurstmeister/kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    networks:
      - distributed-transactions
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - distributed-transactions
networks:
  distributed-transactions:




