version: '3.7'

services:
  transactions_db:
    image: mysql:8.0.18
    container_name: 'transactions-db'
    command: ['--default-time-zone=+8:00']
    environment:
      MYSQL_ROOT_PASSWORD: admin-root
    volumes: # docker volume ls, docker inspect {volumeId} to check location of volumes
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - 3308:3306 # hostPort:containerPort
    networks:
      - distributed-transactions
networks:
  distributed-transactions:




